name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo

jobs:
  ubuntu-build:
    name: ${{ matrix.compiler }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        compiler: [g++-8, g++-9, g++-10, g++-11,
                   clang++-7, clang++-8, clang++-9, clang++-10, clang++-11, clang++-12]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    env:
      CXX: ${{ matrix.compiler }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get -qy install software-properties-common
        sudo add-apt-repository -ny ppa:named-data/ppa
        sudo apt-get -qq update
        sudo apt-get -y install build-essential pkg-config cmake doxygen python3-pip \
                                python3-minimal libboost-all-dev libsqlite3-dev libpcap-dev \
                                libssl-dev libsodium-dev libz-dev liblog4cxx-dev libgtest-dev libfl-dev $CXX

    - name: Install OpenABE
      run: |
        sudo -E ./deps/install_pkgs.sh
        . ./env

        cd deps/relic
        make
        cd ../..

        NO_DEPS=1 BISON=$(which bison) make
        make test
        sudo -E make install

  macos-build:
    name: Xcode ${{ matrix.xcode }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-11 ]
        xcode: [ '12.4', '12.5', '13.2' ]
        include:
          - os: macos-12
            xcode: '13.4'
          - os: macos-12
            xcode: '14.2'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure googletest
        run: |
          cd ..
          wget https://github.com/google/googletest/archive/refs/tags/release-1.12.1.tar.gz
          tar -xzvf release-1.12.1.tar.gz
          cd googletest-release-1.12.1
          mkdir build
          cd build
          cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release ..
          make
          sudo make install
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make
          sudo make install
          cd ../..

      - name: Install dependencies
        run: |
          FORMULAE=(boost openssl pkg-config bison gsed)
          # GitHub Actions runners have a large number of pre-installed
          # Homebrew packages. Don't waste time upgrading all of them.
          brew list --versions "${FORMULAE[@]}" || brew update
          for FORMULA in "${FORMULAE[@]}"; do
            brew list --versions "$FORMULA" || brew install "$FORMULA"
          done
          # Ensure /usr/local/opt/openssl exists
          brew reinstall openssl openssl@1.1

      - name: Install OpenABE
        run: |
          sudo -E ./deps/install_pkgs.sh
          . ./env

          cd deps/relic
          PATH="$(brew --prefix)/opt/gnu-sed/libexec/gnubin:$PATH" make
          cd ../..

          ln -sf /usr/local/opt/openssl@1.1/include/openssl /usr/local/include
          ln -sf /usr/local/opt/openssl@1.1/lib/lib* /usr/local/lib
          NO_DEPS=1 BISON="$(brew --prefix bison)/bin/bison" make
          make test
          sudo -E make install
        env:
          LDFLAGS: "-L/usr/local/opt/openssl@1.1/lib"
